### ISSUE TITLE
Make rendering faster

### ISSUE THREAD

**Issue by ryanwr** [ensignia/tempesta#1]

**Comment by marcellodebernardi** [comment]
I've got an idea for retaining the bilinear interpolation but making it faster. For each data point in the grid there are some constants that are used every time a bilinear interpolation is performed. Those constants could be calculated for each data point once and stored in the grid.

Essentially, perform 2/3 of the algorithm only once and the remaining 1/3 on request. I'll see how that works.

**Comment by ryanwr** [comment]
Added clustering and multi processing for generating tiles, server appears to load faster

**Comment by marcellodebernardi** [comment]
Pushed the fast bilinear interpolation code to a new branch `fastbilinear.` It performs the bilinear interpolation about twice as fast as the previous code but has weird bugs causing corrupted tiles.

Pushed minor, non-controversial changes to the code on develop (`floor()` and `ceil()` to bitwise, no useless divisions by 1 etc).

**Comment by ryanwr** [comment]
This is good enough for now, will reopen if it becomes an issue again or when we get time to review the `fastbilinear` branch
