### ISSUE TITLE
Settings view

### ISSUE THREAD

**Issue by ryanwr** [ensignia/tempesta#14]

**Comment by ryanwr** [comment]
This looks good however I'm not sure the toggle currently fits.

It toggles between an off state (grey) and on state (blue) this doesn't really make sense when switching between units. One doesn't correspond to 'on'. Instead make it both grey in either state for example or use a combo box.

Also the font size needs to match that of the Model/Layers popups

**Comment by marcellodebernardi** [comment]
Both gray is a little confusing in terms of feeling as if though something actually happened. Maybe better to make it two lively, but sort of "opposite" colors? Like red <-> blue?

**Comment by ryanwr** [comment]
True, both blue maybe? 
The other issue with toggle switches is having text either side causes them not to line up nicely, can be fixed but doesn't look very pleasing. 

I suggest one of these
- "Celcius/Fahrenheit       (toggle)"  - The text is on the left separated by a slash
- Use a drop down menu
- Use a pair of radio buttons as its only 2 options
