### ISSUE TITLE
Investigate weather animation synchronization

### ISSUE THREAD

**Issue by marcellodebernardi** [ensignia/tempesta#15]
![image](https://cloud.githubusercontent.com/assets/16990733/23686025/1ff18754-039f-11e7-9fc0-49cf30cae580.png)

Weather animation is out of sync: some tiles are displaying data from one time step, some tiles from another. Not a rendering issue: the tiles line up well, but the correct adjacent tiles are displayed in mismatched steps in the animation.

The issue has never showed up when running a single server locally - maybe the problem is caused by the tile requests being served by separate tempesta instances independently?

**Comment by ryanwr** [comment]
Should be fixed, the live server hasn't been updated in about a day, will test tomorrow.

**Comment by ryanwr** [comment]
Looks fixed now
