### ISSUE TITLE
Add lightning overlay

### ISSUE THREAD

**Issue by ryanwr** [ensignia/tempesta#4]

**Comment by marcellodebernardi** [comment]
Added server-side lightning data generation. Storms appear randomly, die out, move around the map at varying speeds, have varying intensities and varying radii. The API exposes the ability to obtain every global lightning strike within a millisecond-precision time range.

More fine-tuning is required, but in principle we're ready to display lightning data on the map.

**Comment by ryanwr** [comment]
Add pulse animation
